import type { Endpoint } from "../../stores/app";

export const sscEndpoints: Endpoint[] = [
  {
    name: "UpdatePlayer",
    endpoint: "/rpc/player.ext.v1.PrivateService/UpdatePlayer",
    method: "POST",
    bodyParams: {
      name: {
        name: "name",
        regex: "^[a-zA-Z]{2,15}$",
        type: "string",
        required: true,
        example: "StylingeDino",
        desc: "No spaces and 2-15 only alphabet letters",
      },
      level: {
        name: "level",
        regex: "^(0|100|[1-9][0-9]?)$",
        type: "int",
        example: "1",
        default: "",
        desc: "The limit is 0-100 When empty default is 0",
      },
      highscore: {
        name: "highscore",
        regex: "^(0|[1-9][0-9]{0,9})$",
        type: "int",
        example: "100",
        desc: "The limit is 0-2500000000 When empty default is 0",
      },
      metadata: {
        name: "metadata",
        type: "list",
        metadata: {
          HighScoreCharacterKey: {
            name: "HighScoreCharacterKey",
            type: "string",
            example: "DataTag(-1505268145)",
            desc: "The selected character",
          },
          AvatarKey: {
            name: "AvatarKey",
            regex: "^Avatar(?:[1-9]|1[0-3])?$",
            type: "string",
            example: "Avatar1",
            desc: "The selected Avatar",
          },
        },
      },
    },
    requestType: "player.ext.v1.UpdatePlayerRequest",
    responseType: "player.ext.v1.UpdatePlayerResponse",
    type: "rpc",
  },
  {
    name: "CreatePlayer",
    endpoint: "/rpc/player.ext.v1.PrivateService/CreatePlayer",
    method: "POST",
    desc: "This endpoint will not work with a existing account, only a new one.",
    bodyParams: {
      name: {
        name: "name",
        regex: "^[a-zA-Z]{2,15}$",
        type: "string",
        required: true,
        example: "StylingeDino",
        desc: "No spaces and 2-15 only alphabet letters",
      },
      level: {
        name: "level",
        regex: "^(0|100|[1-9][0-9]?)$",
        type: "int",
        example: "1",
        default: "",
        desc: "The limit is 0-100 When empty default is 0",
      },
      highscore: {
        name: "highscore",
        regex: "^(0|[1-9][0-9]{0,9})$",
        type: "int",
        example: "100",
        desc: "The limit is 0-2500000000 When empty default is 0",
      },
      metadata: {
        name: "metadata",
        type: "list",
        metadata: {
          HighScoreCharacterKey: {
            name: "HighScoreCharacterKey",
            type: "string",
            example: "DataTag(-1505268145)",
            desc: "The selected character",
          },
          AvatarKey: {
            name: "AvatarKey",
            regex: "^Avatar(?:[1-9]|1[0-3])?$",
            type: "string",
            example: "Avatar1",
            desc: "The selected Avatar",
          },
        },
      },
    },
    requestType: "player.ext.v1.CreatePlayerRequest",
    responseType: "player.ext.v1.CreatePlayerResponse",
    type: "rpc",
  },
  {
    name: "GetPlayer",
    endpoint: "/rpc/player.ext.v1.PrivateService/GetPlayer",
    method: "POST",
    desc: "Retrieve the authenticated player's profile.",
    bodyParams: {},
    requestType: "player.ext.v1.GetPlayerRequest",
    responseType: "player.ext.v1.GetPlayerResponse",
    type: "rpc",
  },
  {
    name: "GetPlayerByTag",
    endpoint: "/rpc/player.ext.v1.PrivateService/GetPlayerByTag",
    method: "POST",
    bodyParams: {
      tag: {
        name: "playertag",
        regex: "^[A-Z0-9]{14}$",
        type: "string",
        required: true,
        example: "BY1BJH84CVHHIX",
      },
    },
    desc: "Retrieve a player by their public playertag.",
    requestType: "player.ext.v1.GetPlayerByTagRequest",
    responseType: "player.ext.v1.GetPlayerByTagResponse",
    type: "rpc",
  },
  {
    name: "GetPlayerById",
    endpoint: "/rpc/player.ext.v1.PrivateService/GetPlayerById",
    method: "POST",
    bodyParams: {
      uid: {
        name: "playeruuid",
        regex: "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$",
        type: "string",
        required: true,
        example: "0197351b-ae06-7a3f-8576-0e3d5b95a280",
      },
    },
    desc: "Retrieve a player by their UUID.",
    requestType: "player.ext.v1.GetPlayerByIdRequest",
    responseType: "player.ext.v1.GetPlayerByIdResponse",
    type: "rpc",
  },
  {
    name: "GetScores",
    endpoint: "/rpc/leaderboard.ext.v1.PrivateService/GetScores",
    method: "POST",
    bodyParams: {
      "leaderboard.id": {
        name: "Leaderboard ID",
        type: "string",
        required: true,
        example: "top_run_weekly_v2",
        default: "top_run_weekly_v2",
        desc: "Leaderboard identifier.",
      },
      "leaderboard.partitions.partitionStrings.0.key": {
        name: "Partition String Key",
        type: "string",
        required: true,
        example: "cc",
        default: "cc",
        desc: "String partition key.",
      },
      "leaderboard.partitions.partitionStrings.0.value": {
        name: "Partition String Value",
        type: "string",
        required: true,
        example: "us",
        default: "us",
        desc: "String partition value.",
      },
      "leaderboard.partitions.partitionIntegers.0.key": {
        name: "Partition Integer Key",
        type: "string",
        required: true,
        example: "lvl",
        default: "lvl",
        desc: "Integer partition key.",
      },
      "leaderboard.partitions.partitionIntegers.0.value": {
        name: "Partition Integer Value",
        type: "int",
        required: true,
        example: 50,
        default: 50,
        desc: "Integer partition value.",
      },
    },
    desc: "Retrieve leaderboard scores for a request like top_run_weekly_v2 with cc=us and lvl=50.",
    requestType: "leaderboard.ext.v1.GetScoresRequest",
    responseType: "leaderboard.ext.v1.GetScoresResponse",
    type: "rpc",
  },
  {
    name: "SubmitScore",
    endpoint: "/rpc/leaderboard.ext.v1.PrivateService/SubmitScore",
    method: "POST",
    bodyParams: {
      "tournament.id": {
        name: "Tournament ID",
        type: "string",
        required: true,
        example: "top_run_v1",
        desc: "Tournament identifier (e.g., top_run_v1).",
      },
      "pool.partitionKey": {
        name: "Pool Partition Key",
        type: "string",
        required: true,
        example: "default",
        desc: "Pool partition key (e.g., default).",
      },
      "pool.countryCodePartitionKey": {
        name: "Country Code Partition Key",
        type: "string",
        required: false,
        example: "us",
        regex:
          "^(?:ad|ae|af|ag|ai|al|am|ao|aq|ar|at|au|aw|az|ba|bb|bd|be|bf|bg|bh|bj|bn|bo|br|bs|by|bz|ca|cf|ch|ci|cl|cn|co|cr|cu|cy|cz|de|dk|do|dz|ec|ee|eg|er|es|et|fi|fj|fr|gb|ge|gh|gr|gt|gy|hk|hn|hr|ht|hu|id|ie|il|in|iq|ir|is|it|jm|jo|jp|ke|kg|kh|ki|kn|kp|kr|kw|kz|la|lb|lc|li|lk|lt|lu|lv|ly|ma|md|me|mk|ml|mm|mn|mr|mt|mu|mv|mx|my|mz|na|ng|ni|nl|no|np|nr|nz|om|pa|pe|ph|pk|pl|ps|pt|py|qa|ro|rs|ru|sa|sd|se|sg|si|sk|sn|sr|ss|sv|sy|th|tj|tm|tn|tr|tt|tv|tw|tz|ua|ug|us|uy|uz|vc|ve|vn|ye|za|zm|zw)$",
        desc: "Country code partition key (e.g., us).",
      },
      "score.value": {
        name: "Score Value",
        regex: "^([0-9]|[1-8][0-9]|90)$",
        type: "int",
        required: false,
        example: 50,
        desc: "The limit is 0-90",
      },
      "score.gameplayDuration.seconds": {
        name: "gameplayDuration.seconds",
        type: "int",
        required: false,
        example: 100,
      },
      "score.gameplayDuration.nanos": {
        name: "gameplayDuration.nanos",
        type: "int",
        required: false,
        example: 100,
      },
      "score.scoredAt.seconds": {
        name: "scoredAt.seconds",
        type: "int",
        required: false,
        example: 100,
      },
      "score.scoredAt.nanos": {
        name: "scoredAt.nanos",
        type: "int",
        required: false,
        example: 100,
      },
    },
    desc: "Submit a player's score to the tournament leaderboard.",
    requestType: "tournament.ext.v2.SubmitScoreRequest",
    responseType: "tournament.ext.v2.SubmitScoreResponse",
    type: "rpc",
  },
  {
    name: "MatchExperiments",
    endpoint: "/rpc/abtesting.ext.v2.PrivateService/MatchExperiments",
    method: "POST",
    bodyParams: {
      "metrics.language": {
        name: "Language",
        type: "string",
        required: true,
        example: "en",
        default: "en",
        desc: "Language metric.",
      },
      "metrics.age": {
        name: "Age",
        type: "string",
        required: true,
        example: "34",
        default: "34",
        desc: "Age metric as a string.",
      },
      "metrics.platform": {
        name: "Platform",
        type: "string",
        required: true,
        example: "android",
        default: "android",
        desc: "Platform metric.",
      },
      "metrics.coppa": {
        name: "COPPA",
        type: "string",
        required: true,
        example: "false",
        default: "false",
        desc: "COPPA flag as a string.",
      },
      "metrics.gameVersion": {
        name: "Game Version",
        type: "string",
        required: true,
        example: "2.1.0",
        default: "2.1.0",
        desc: "Game version metric.",
      },
    },
    desc: "Match experiments using metrics like language, age, platform, coppa, and gameVersion.",
    requestType: "abtesting.ext.v2.MatchExperimentsRequest",
    responseType: "abtesting.ext.v2.MatchExperimentsResponse",
    type: "rpc",
  },
  {
    name: "GDPRDelete",
    endpoint: "/v1.0/gdpr/delete",
    method: "POST",
    bodyParams: {
      gaid: {
        name: "gaid",
        type: "string",
        required: true,
        example: "00000000-0000-0000-0000-000000000000",
        desc: "",
      },
    },
    desc: "Request deletion of a player's data under GDPR regulations. This is a long-running operation; use GDPRStatus to check progress.",
    requestType: "",
    responseType: "",
    type: "json",
  },
  {
    name: "GDPRStatus",
    endpoint: "/v1.0/gdpr/status",
    method: "GET",
    desc: "Check the GDPR deletion status for a player.",
    requestType: "",
    responseType: "",
    type: "json",
  },
  {
    name: "Register",
    endpoint: "/v2.0/auth/register",
    method: "POST",
    desc: "Register a new player.",
    requestType: "",
    responseType: "",
    type: "json",
  },
  {
    name: "Refresh",
    endpoint: "/v2.0/auth/refresh",
    method: "POST",
    bodyParams: {
      refreshToken: {
        name: "refreshToken",
        type: "string",
        required: true,
        example: "eyJhbGciOiJQUzI1NiIsInR5cC...",
        desc: "",
      },
    },
    desc: "Refresh a player's authentication token.",
    requestType: "",
    responseType: "",
    type: "json",
  },
  {
    name: "Profile",
    endpoint: "/v2.0/profile",
    method: "GET",
    desc: "Retrieve the player's profile.",
    requestType: "",
    responseType: "",
    type: "json",
  },
  {
    name: "ProfileById",
    endpoint: "/v2.0/profile/:uuid",
    method: "GET",
    pathParams: {
      uuid: {
        name: "uuid",
        type: "string",
        required: true,
        regex:
          "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
        example: "123e4567-e89b-12d3-a456-426614174000",
        desc: "Player UUID",
      },
    },
    desc: "Retrieve a player's profile by UUID.",
    requestType: "",
    responseType: "",
    type: "json",
  },
];
